name: ayumc_server
description: Core Minecraft server implementation in Dart
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.10.4

dependencies:
  ayumc_api:
    path: ../api
  ayumc_plugin_loader:
    path: ../plugin_loader

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

